# Generated by Django 5.0.4 on 2024-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
