# Generated by Django 5.0.4 on 2024-04-28 19:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_profile_img_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=account.models.upload_location, verbose_name='Profile Image'),
        ),
    ]
